### PR TITLE
Set up PCB for M.2 Type 3042-S3 form factor.

### PR DESCRIPTION
**Pull request by martinling**
I've set up the board with the correct outline, keepout areas, and mechanical ground pad for the M.2 3042-S3 form factor.

image

### CODE REVIEW

**Comment by sp5wwp** [comment]
u.FL is too big and placed in the wrong place. We probably need to use MHF4 connector, close to the board's edge.

**Comment by n1zzo** [comment]
Well done martling 😁
Can the antenna connector be placed in the keepout area near the semicircle screw hole?
I believe other WWAN adapters do this.
Also because we will cover everything with an RF shield except the keepout area.

**Comment by f-izzo** [comment]
Thank you @martinling for the Pull Request, I will merge it right away.
@n1zzo I will move the antenna connector, @sp5wwp I can change the connector to MHF4

**Comment by martinling** [comment]
All I was doing was setting up the board area, I didn't want to touch the schematics & footprints in the same change.

Yes, the connector needs to be changed to MHF4 as I said in the channel. Then it can be placed in the 3.8mm wide red zone on the right, which is designated in the standard as for RF connectors only.

I had a look for suitable RF shields but I'm not seeing much off the shelf. The height limit for this form factor is 1.5mm and most available shields are a lot taller than that. Usually something custom would be used for a card like this.

For prototyping, a DIY shield can be made. If a production run eventually gets done, it is not too difficult/costly to have custom shields made. See e.g. https://www.sparkfun.com/news/3123

**Pull request merged**
